## HOMEWORK

### Exercise 1

Try to use the dataset URLs.PASCAL_2007 to find the masks

In [ ]:
from fastai.vision.all import *
from fastcore.all import *

path1 = untar_data(URLs.PASCAL_2007)
dls1 = SegmentationDataLoaders.from_label_func(
    path1, bs = 8, fnames = get_image_files(path1/"train"),
    label_func = lambda o: path1/'segmentation'/f'{o.stem}_P{o.suffix}',
    codes = ['Background', 'Person', 'Animal', 'Vehicle', 'Object']
)

In [ ]:
dls1.show_batch(max = 12)

In [ ]:
learn1= unet_learner(dls1, resnet34)
learn1.fine_tune(3)

In [ ]:
learn1.show_results()

### Exercise 2

Apply the tabular model to following dataset 

URL: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

1. Find which chemical parameters influence the **quality** of the wine
2. Write the function **predict_wine(alcohol, ph, acidity)** that returns the quality of the wine
3. Find the wines where the model went the wrong way the most

In [ ]:
from fastai.tabular.all import *
from fastai.vision.all import *
import csv


url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

df = pd.read_csv(url, sep = ";")
print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076
1            7.8              0.88         0.00             2.6      0.098
2            7.8              0.76         0.04             2.3      0.092
3           11.2              0.28         0.56             1.9      0.075
4            7.4              0.70         0.00             1.9      0.076

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68
2                 15.0                  54.0   0.9970  3.26       0.65
3                 17.0                  60.0   0.9980  3.16       0.58
4                 11.0                  34.0   0.9978  3.51       0.56

   alcohol  quality
0      9.4        5
1      9.8        5
2      9.8        5
3      9.8        6
4      9.4        5

In [28]:
df.to_csv("wine.csv", index = False)

In [21]:
dls2 = TabularDataLoaders.from_df(
    df,
    cont_names = ["fixed acidity", "volatile acidity", "citric acid", "residual sugar", 
                 "chlorides", "sulphates", "alcohol"],
    cat_names = [],
    y_names = "quality",
    procs = [FillMissing, Normalize]
)

dls2.show_batch()

In [24]:
learn2 = tabular_learner(dls2, metrics = rmse) # rmse -> Root Mean Squared Error
learn2.fit_one_cycle(3)

<div><div><progress max="3" value="0"></progress> 0.00% [0/3 00:00&lt;?]</div><div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>_rmse</th><th>time</th></tr></thead><tbody></tbody></table></div><div><progress max="20" value="0"></progress> 0.00% [0/20 00:00&lt;?]</div></div>

In [25]:
learn2.show_results()